apiVersion: 1

deleteDatasources:
  - name: Prometheus
    orgId: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    uid: prometheus
    url: http://prometheus:9090
    basicAuth: false
    isDefault: true
    version: 1
    editable: false
    jsonData:
      httpMethod: POST
      timeInterval: "15s"
      queryTimeout: "30s"
      manageAlerts: true
      prometheusType: Prometheus
      prometheusVersion: 2.44.0
      exemplarTraceIdDestinations:
        # Add trace ID destination for distributed tracing (can be added later)
        # - name: trace_id
        #   datasourceUid: tempo
    secureJsonData:
      # Add any secure fields here if needed
      # httpHeaderValue1: "secret-value"